Upgrade tar dependency to v7.x
doapp-ryanp/dynamodb-local pull request #54
Opened 2024-09-04 16:46 UTC by WtfJoke

Dropping support for node 6 and 8 (as tar v6 drops that support as well).
Addresses [CVE-2024-28863](https://github.com/advisories/GHSA-f5x3-32g6-xq36)

2024-09-04 18:36 UTC, rynop requested changes
LGTM after comment!

2024-09-04 18:36 UTC, rynop commented on package.json
> +    "tar": "^7.4.3"
I'm not a fan of `^` as it can introduce breaking changes
```suggestion
    "tar": "~7.4.3"
```

2024-09-04 18:49 UTC, WtfJoke commented
Thanks for your fast answer. Commited your suggested change with your comment! Looking forward to merge and release!

2024-09-04 19:44 UTC, rynop approved these changes

2024-09-04 19:44 UTC, merged

2024-09-04 19:47 UTC, rynop commented
Version `0.0.35` published: https://www.npmjs.com/package/dynamodb-local

thanks!

2024-09-05 08:08 UTC, WtfJoke commented
Thank you for the fast release <3